// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gccmqkrshinbdvszkegh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdjY21xa3JzaGluYmR2c3prZWdoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI0MzQ2OTgsImV4cCI6MjA2ODAxMDY5OH0.PGL6XvmAl4vPPJSqPCNtD4yH32oI8diOguBoElc20AQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});