// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yechgqhfkbshnjyklphn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InllY2hncWhma2JzaG5qeWtscGhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM3MjY2NTcsImV4cCI6MjA2OTMwMjY1N30.csXgDBocq-ZNJ2WSr8gI5p5LUu7u5Edey8YzwRGjC5Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});